Deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -151,15 +151,15 @@ jobs:
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
               #exit 1
-      # - run:
-      #     name: Ensure front-end infrastructure exist
-      #     command: |
-      #       aws cloudformation deploy \
-      #         --template-file .circleci/files/frontend.yml \
-      #         --tags project=project3 \
-      #         --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-      #         --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
-      #         #exit 1
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=project3 \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+              #exit 1
       - run:
           name: Add back-end ip to ansible inventory
           command: |
@@ -215,18 +215,8 @@ jobs:
           command: |
             # Your code here
             cd backend
-            # echo "--------clean --force--------"
-            # npm cache clean --force
             echo "--------install dependencies--------"
             npm install
-            # echo "--------export PATH--------"
-            # export PATH="$PATH:./node_modules/typescript/bin"
-            # echo "--------tsc --version--------"
-            # pwd
-            # tsc --version
-            # echo "--------NODE_ENV--------"
-            # echo $NODE_ENV
-            # Run and save the migration output
             echo "--------run migrations--------"
             npm run migrations > migrations_dump.txt
             #exit 1
@@ -307,9 +297,6 @@ jobs:
             cd ..
             tar -C backend -czf artifact.tar.gz .
             pwd
-            # mv artifact.tar.gz .circleci/ansible/roles/deploy/files
-            # cd .circleci/ansible/roles/deploy/files
-            # pwd
             echo "--------go to ansible--------"
             cd .circleci/ansible
             pwd
@@ -327,19 +314,19 @@ jobs:
           command: |
             # your code here
             yum -y install tar gzip curl
-      # - run:
-      #     name: Backend smoke test.
-      #     command: |
-      #       # your code here
-      #       # Fetch and prepare the BACKEND_IP env var
-      #       export API_URL="http://${BACKEND_IP}:3030"
-      #       echo "${API_URL}"
-      #       if curl "${API_URL}/api/status" | grep "ok"
-      #       then
-      #           return 0
-      #       else
-      #           return 1
-      #       fi
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            # Fetch and prepare the BACKEND_IP env var
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                return 0
+            else
+                return 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
@@ -416,34 +403,31 @@ workflows:
   default:
     jobs:
       - build-frontend
-      # - build-backend
-      # - test-frontend:
-      #     requires: [build-frontend]
-      # - test-backend:
-      #     requires: [build-backend]
-      # - scan-backend:
-      #     requires: [build-backend]
-      # - scan-frontend:
-      #     requires: [build-frontend]
-      # - deploy-infrastructure:
-      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      #     filters:
-      #       branches:
-      #         only: [circleci-project-setup]
-      # - deploy-infrastructure
-      # - configure-infrastructure:
-      #     requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
-      # - run-migrations
-      # - deploy-frontend:
-      #     requires: [deploy-infrastructure]
-      # - deploy-backend:
-      #     requires: [configure-infrastructure]              
-      # - smoke-test:
-      #     requires: [deploy-infrastructure]     
-      # - cloudfront-update:
-      #     requires: [smoke-test] 
-      # - cloudfront-update:
-      #     requires: [deploy-backend] 
-      # - cleanup
+      - build-backend
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
+      - scan-backend:
+          requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [circleci-project-setup]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]              
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]  
+      - cloudfront-update:
+          requires: [smoke-test] 
+      # - cleanup:
+      #     requires: [cloudfront-update]
